### PR TITLE
Fix dirty attribute changes on update

### LINKED ISSUE #1133: Model save erroneously sends unchanged attributes to API
# Issue summary

There are a number of issues coming from the shopify gem erroneously sending the entire object when saving as outlined here almost 6 months ago: https://github.com/Shopify/shopify-api-ruby/issues/1037

The gem should only send the changed attributes to the API, but it sends all fields, leading to API errors.

Changing/Saving any part of a Customer created without an email (phone number only) through the checkout will return
`{"email_marketing_consent"=>["An email address is required when setting the email marketing consent."]}`

Changing/Saving any part of a Customer with a nil email_marketing_consent.opt_in_level will return
`{"email_marketing_consent"=>["Opt in level must exist"]}`

Changing/Saving any part of an Order (maybe from POS?) without a shipping address will return
`{"shipping_address"=>[": Enter a last name."]}`

- `shopify_api` version: 12.3.0
- Ruby version: 2.7.2
- Operating system: All

## Expected behavior

The gem should only send the changed attributes on save, as outlined in https://github.com/Shopify/shopify-api-ruby/issues/1037

## Actual behavior

The gem sends all attributes leading to api errors.

## Steps to reproduce the problem

see  https://github.com/Shopify/shopify-api-ruby/issues/1037

### PR DESCRIPTION
**Pull request by nelsonwittwer**
## Description

Fixes #1133 and #1037 which both report a substantial issue with tracking what attributes were actually modified by the user since the rest resources were initialized.

The root cause of this issue, as pointed out by @kaarelss, was symbols vs hashes when comparing drift on attributes 🤦 . I also needed to 1) set associations in `original_state` since our API allows us to modify associated resources and 2) needed to ignore read only attributes in `original_state`.

## How has this been tested?

- Wrote a unit test that reproduced the issue. The fix was then applied to the base rest resource which passed the test.
- In a local environment using this branch of the ruby API library, I found an existing product and updated a single attribute. I compared all other attributes and verified only the single attribute was modified.

## Checklist:

- [x] My commit message follow the pattern described in [here](https://chris.beams.io/posts/git-commit/)
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the project documentation.
- [x] I have added a changelog line.

### CODE REVIEW

**Review by wayne692 — COMMENTED** [review]
It's easy

File: lib/shopify_api/rest/base.rb [hunk 1]
```diff
@@ -234,16 +234,20 @@ def create_instance(data:, session:, instance: nil)
...
               end
               instance.public_send("#{attribute}=", attr_list)
             elsif has_one?(attr_sym) && value
               # force a hash if core returns values that instantiate objects like "USD"
               data_hash = value.is_a?(Hash) ? value : { attribute.to_s => value }
-              instance.public_send("#{attribute}=",
-                T.unsafe(@has_one[attr_sym]).create_instance(data: data_hash, session: session))
+              child = T.unsafe(@has_one[attr_sym]).create_instance(data: data_hash, session: session)
+              instance.public_send("#{attribute}=", child)
+              instance.original_state[attr_sym] = child.to_hash(true)
```
Comment (DuncanUszkay1) [inline lib/shopify_api/rest/base.rb:250]: This was a breaking change for our application that went unreported in the changelog. We were creating an instance and immediately calling save on it, which with this change resulted in an empty array being sent to Shopify.

Comment (DuncanUszkay1) [reply lib/shopify_api/rest/base.rb:250]: Not sure if we were using the library improperly since I didn't see mention of this is the docs, but if not I can go update the changelog for others who might run into this.
